name: Lex-Bot Deployment

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
          unzip terraform_1.0.9_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      - name: Initialize Terraform
        run: terraform init
      - name: Check orderbot.tf is present
        run: ls orderbot.tf
      - name: Validate Terraform configuration
        run: terraform validate
      - name: Plan Terraform configuration
        run: terraform plan -out=tfplan
      # - name: Destroy Stack
      #   run: terraform destroy --auto-approve
      - name: Deploy terraform manifest
        run: terraform apply --auto-approve